package com.raven.Form;

import java.awt.Color;
import javax.swing.JDialog;

/**
 *
 * @author Bước Chân Của Đam Mêêêê
 */
public class WellcomesJDialog extends javax.swing.JDialog {

    /**
     * Creates new form SplashScreen
     */
    public WellcomesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(221, 221, 221));
        //  To disable key Alt+F4 to close dialog
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblShop = new javax.swing.JLabel();
        curvesPanel1 = new com.raven.Wellcomes.CurvesPanel();
        pro = new com.raven.Wellcomes.ProgressBarCustom();
        lblStatus = new javax.swing.JLabel();
        lblShop1 = new javax.swing.JLabel();

        lblShop.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblShop.setForeground(new java.awt.Color(0, 255, 255));
        lblShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/Icon/RavenXanh.png"))); // NOI18N
        lblShop.setText("SHOP BCCDM");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EduSys");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pro.setBackground(new java.awt.Color(102, 255, 255));

        lblStatus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(51, 51, 51));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Status");

        lblShop1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblShop1.setForeground(new java.awt.Color(102, 102, 102));
        lblShop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/Icon/RavenXanh2.png"))); // NOI18N
        lblShop1.setText("BƯỚC CHÂN CỦA ĐAM MÊ");

        javax.swing.GroupLayout curvesPanel1Layout = new javax.swing.GroupLayout(curvesPanel1);
        curvesPanel1.setLayout(curvesPanel1Layout);
        curvesPanel1Layout.setHorizontalGroup(
            curvesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblShop1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(curvesPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        curvesPanel1Layout.setVerticalGroup(
            curvesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, curvesPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblShop1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curvesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(curvesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    doTask("Đang khởi chạy...", 1);
                    doTask("Đang khởi chạy...", 2);
                    doTask("Đang khởi chạy...", 3);
                    doTask("Đang khởi chạy...", 4);
                    doTask("Đang khởi chạy...", 5);
                    doTask("Đang khởi chạy...", 6);
                    doTask("Đang khởi chạy...", 7);
                    doTask("Đang khởi chạy...", 8);
                    doTask("Đang khởi chạy...", 9);
                    doTask("Đang khởi chạy...", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 10);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 21);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 21);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 21);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 22);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 22);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 22);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 22);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 23);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 23);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 23);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 23);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 24);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 24);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 24);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 24);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 25);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 25);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 26);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 27);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 27);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 29);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 30);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 31);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 32);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 33);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 50);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 60);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 70);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 80);
                    doTask("Đang tải tài nguyên(không tốn dung lượng)", 90);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Tải tài nguyên hoàn tất", 95);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    doTask("Bước Chân Của Đam Mêêêê", 100);
                    dispose();
                    curvesPanel1.stop();//Dừng hiệu ứng    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }//GEN-LAST:event_formWindowOpened

    private void doTask(String taskName, int progress) throws Exception {
        lblStatus.setText(taskName);
        Thread.sleep(35); //  For Test
        pro.setValue(progress);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WellcomesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WellcomesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WellcomesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WellcomesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WellcomesJDialog dialog = new WellcomesJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.Wellcomes.CurvesPanel curvesPanel1;
    private javax.swing.JLabel lblShop;
    private javax.swing.JLabel lblShop1;
    private javax.swing.JLabel lblStatus;
    private com.raven.Wellcomes.ProgressBarCustom pro;
    // End of variables declaration//GEN-END:variables
}
